[Maintenance] Update to Vue 3.4 and introduce defineModel #175
it-at-m/refarch-templates pull request #179
Opened 2024-08-08 12:22 UTC by langehm

**Description**
- updated dependency
- replaced props and emits of modelValue with defineModel
- removed two-way binding of dialog instead of replacing it with defineModel

Issues #175

2024-08-08 14:10 UTC, devtobi requested changes

2024-08-08 14:10 UTC, devtobi commented on refarch-frontend/package.json
You mentioned vue-tsc 1.8.27 and vite vue plugin 5.0.0 is needed. Did you check this? If so, please update those as well to fullfill the requirements.

2024-08-08 14:10 UTC, devtobi commented on refarch-frontend/src/components/common/YesNoDialog.vue
Isn't defineModel needed here as well to be fed into the dialog? Otherwise v-model cannot be used for the YesNoDialog, right?

2024-08-09 10:23 UTC, langehm commented on refarch-frontend/src/components/common/YesNoDialog.vue
The dialog itself does not decide if it should be opened or closed. This action is done by the parent component (the component using the dialog). This is mandatory in case the parent component decides to leave the dialog open even if a button (yes/no) was pressed. 
Such a mechanism (the dialog deciding upon closing himself) was not implemented before - the property (modelValue) was only used in a read-only manor.

Therefore, we can reduce the modelValue from a read/write (defineModel or prop+emit) to a read-only prop.

2024-08-09 10:27 UTC, langehm commented on refarch-frontend/package.json
Both are mentioned with `potentially needed` ... in the next line vue-tsc is marked as `required`.
A bit confusing - try to update both of them?

2024-08-09 11:51 UTC, devtobi commented on refarch-frontend/package.json
Yes I'd endorse that. :)

2024-08-13 06:53 UTC, langehm commented on refarch-frontend/package.json
Updating `vitejs/vue-plugin` causes a welter of changes to multiple dependencies. `Vite` itself needs to be updated to `>=5.X`.
- unplugin-fonts (1.1.0 still has issues with vite@5)
- vuetify
- vite-plugin-vuetify
- vitest
- ...

Should this be adressed in another issue?

2024-08-14 06:55 UTC, devtobi commented on refarch-frontend/package.json
Yes, we will address this in another issuse. We will set your issue + PR to blocked until mergeable. :) Anyways thanks for contributing. ;)

2024-08-22 06:51 UTC, langehm commented on refarch-frontend/package.json
This could be done in retreat!

2024-08-23 13:38 UTC, devtobi commented
Updates to various dependencies were made in https://github.com/it-at-m/refarch-templates/pull/212. Please check if you can implement your feature with the new dependencies now or if additional bumps are required.

2024-09-05 10:11 UTC, devtobi approved these changes
LGTM

2024-09-05 10:19 UTC, closed without merging

2024-09-05 11:22 UTC, devtobi commented
Can only be merged once https://github.com/it-at-m/refarch-templates/issues/290 has been done.