add appswitcher-server to stack, configure appswitcher frontend component via .env
it-at-m/refarch-templates pull request #308
Opened 2024-09-06 14:05 UTC by eidottermihi

**Description**

- adds [appswitcher-server](https://github.com/it-at-m/appswitcher-server) to local stack, containing "apps" of local stack (pgAdmin, Keycloak)
- configuration of appswitcher-server url is done via `.env` files during frontend buildtime
  - dev build: use local instance from stack
  - production build: use LHM-internal instance

![grafik](https://github.com/user-attachments/assets/40e71590-6532-48b5-982d-a31a7693f96e)

**Reference**

Issues #100

2024-09-10 09:53 UTC, devtobi requested changes

2024-09-16 11:12 UTC, eidottermihi commented on stack/appswitcher-server/application.yml
> +    image-url: https://upload.wikimedia.org/wikipedia/commons/a/ad/Logo_PostgreSQL.png
Right now thats not possible with `appswitcher-server`. But as we use those "apps" only for "development" purposes with the local stack I think that's ok.

2024-09-16 11:14 UTC, devtobi commented on stack/appswitcher-server/application.yml
> +    image-url: https://upload.wikimedia.org/wikipedia/commons/a/ad/Logo_PostgreSQL.png
Ok that's fine for now. Still would recommend creating a follow up issue for the repo of `app switcher-server`.

2024-09-16 11:16 UTC, devtobi approved these changes
LGTM

2024-09-16 11:38 UTC, devtobi approved these changes
LGTM, great that static files are working. :)

2024-09-16 11:42 UTC, merged

2024-09-16 11:49 UTC, devtobi commented
Reminder: This PR is also relevant for github.com/it-at-m/refarch